# Generated by Django 4.0.1 on 2022-01-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BangoreJobs',
            new_name='BangloreJobs',
        ),
    ]
